#!/usr/bin/perl
use strict;
use warnings;
use File::Copy;
use JSON;
use Digest::MD5 qw(md5_hex);
use OpenSSL::X509;

# 入参
my $domain = $ARGV[0];
my @files_to_copy = (
    '/path/to/source/wongcw.cn.crt',
    '/path/to/source/wongcw.cn.key',
    '/path/to/source/fullchain.crt',
);
my $destination_dir = "/usr/trim/var/trim_connect/ssls/$domain/";
my @config_files = ('network_cert_all.conf', 'network_gateway_cert.conf');

sub get_cert_dates {
    my ($cert_path) = @_;
    my $cert = OpenSSL::X509->new_from_file($cert_path);
    my $start_date = $cert->get_notBefore();
    my $end_date = $cert->get_notAfter();
    return ($start_date, $end_date);
}

sub calculate_md5 {
    my ($file_path) = @_;
    open(my $fh, "<", $file_path) or die "Cannot open file $file_path: $!";
    binmode($fh);
    my $md5 = md5_hex(do { local $/; <$fh> });
    close($fh);
    return $md5;
}

sub modify_config_files {
    my ($domain, @files_to_copy, $destination_dir, @config_files) = @_;
    foreach my $file (@files_to_copy) {
        copy($file, $destination_dir) or die "Copy failed: $!";
    }

    my ($start_date, $end_date) = get_cert_dates("$destination_dir/wongcw.cn.crt");
    my $sum_value = calculate_md5("$destination_dir/wongcw.cn.crt");

    foreach my $config_file (@config_files) {
        open(my $fh, "<", $config_file) or die "Cannot open file $config_file: $!";
        my $data = do { local $/; <$fh> };
        close($fh);
        my $config = decode_json($data);

        my $existing_cert_found = 0;
        for my $item (@$config) {
            if ($item->{domain} eq "*.$domain") {
                $item->{certificate} = "$destination_dir/wongcw.cn.crt";
                $item->{fullchain} = "$destination_dir/fullchain.crt";
                $item->{privateKey} = "$destination_dir/wongcw.cn.key";
                $item->{validFrom} = $start_date;
                $item->{validTo} = $end_date;
                $item->{sum} = $sum_value;
                $item->{used} = 1;
                $existing_cert_found = 1;
                last;
            }
        }
        unless ($existing_cert_found) {
            push @$config, {
                domain => "*.$domain",
                san => ["*.$domain", $domain],
                certificate => "$destination_dir/wongcw.cn.crt",
                fullchain => "$destination_dir/fullchain.crt",
                privateKey => "$destination_dir/wongcw.cn.key",
                validFrom => $start_date,
                validTo => $end_date,
                sum => $sum_value,
                used => 1,
                appFlag => 0
            };
        }

        open(my $fh, ">", $config_file) or die "Cannot open file $config_file: $!";
        print $fh encode_json($config);
        close($fh);
    }
}

modify_config_files($domain, @files_to_copy, $destination_dir, @config_files);
